### PR TITLE
Refactor/decouple

### PR DESCRIPTION
**Pull request by SiC42**
Decouple system from DBOIndex and FOX.
Instead, there is now a new interface called TaskInterface.
Implementations of this interface should be used to change the tokens in the processing pipeline. This means that FOX and DBOIndex could be implemented anew with that interface. For now there are 2 implementaions:
- StanfordNLP, which takes the initial question and creates tokens containing various NLP information (e.g. POS-tags)
- Autoindex, which also considers the question and queries an Autoindex-endpoint via REST. The result are n-grams containing URIs, which will be merged with the given tokens to combine bigger tokens (e.g. "Angela" & "Merkel" to "Angela Merkel")

### CODE REVIEW

**Comment by SiC42** [comment]
@RicardoUsbeck Feel free to merge. However, consider that this means that the master will be almost unusable for now (at least if you do not know the limitations), because the rest of the system still works with DBpedia (see e.g. #2) and Queries.json has english POS-tags, while the implementation of StanfordNLP provides german POS-tags

**Comment by sajjadpz** [comment]
@SiC42 , do we have yet a way to check an end to end request somehow(surnia-->autoIndex)? As you mentioned it is unusable and so have I tested, and it fails because it still expects tokens to be parsed according to `dbpedia` implementation.

**Comment by SiC42** [comment]
I made a test which can be used:
https://github.com/dice-group/SurniaQA/blob/9b55b6bb4f41c18774a31fe123e79830f54874ba/src/test/java/de/upb/ds/surnia/preprocessing/tasks/AutoindexTaskTest.java#L62-L80

Basically just make a new test-method which calls the AutoindexTask-constructor with the REST-API-URL (see class itself for info) and have the two mentioned entries in your autoindex-db (i.e. "age->foaf:age" and "Angela Merkel->dbr:Angela_Merkel" {and i mean literally these entries, not the real url like http://dbpedia.org/resource/Angela_Merkel}) or make your own little test case based on this one.

If you have further questions feel free to contact me.

**Comment by RicardoUsbeck** [comment]
From here on, this branch is handed over to @sajjadpz  and Nesara and ask them to finish the refactoring, so it works with arbitrary knowledge bases and SASK in particular. Thus this merge will be open but no further work from you @SiC42  is required

**Comment by sajjadpz** [comment]
@SiC42 - The test case structure you have mentioned executes following query on `Autoindex`
`Wie alt ist Angela Markel?"` which is not `tokenized` and would not probably return required `URIs`.

**Comment by SiC42** [comment]
But it does:
image

**Comment by sajjadpz** [comment]
Yeah, but isn't it too specific for the format of data that you have mentioned? what steps do you think are the next to make it more general?

**Comment by SiC42** [comment]
Can you open a issue and elaborate your question? Preferably with a little example

**Pull request merged**
